[METABOX] ADD : bookings/views.py 작성&로그인 데코레이터 작성 & 모델 일부 수정
wecode-bootcamp-korea/24-2nd-METABOX-backend pull request #3
Opened 2021-09-17 04:21 UTC by Oraange

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 예매에 관한 view작성
- 로그인 데코레이터 작성
- 모델 일부 수정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 예매 관련한 post Method와 get Method 작성
- 로그인 데코레이터 작성 
- 좌석(seat number) 테이블을 따로 빼냈습니다. 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-17 04:23 UTC, Oraange commented
unit test는 작성 전입니다. 작업 중에 계속 기능을 바꿔야 하는 부분이 생겨서 일단 PR요청 해놓고 나중에 unit test한 결과를 rebase로 커밋 합치겠습니다.

2021-09-17 06:39 UTC, S2-J1NG requested changes
model 수정 사항은 새로 브랜치 생성해서 작업하고 PR 요청 해주세요!
기능 브랜치에는 유닛테스트 없으면 머지가 안 됩니다!

2021-09-17 06:39 UTC, S2-J1NG commented on bookings/views.py
> +                kid              = kid
성인 1명일 경우 teenager와 kid 는 null로 처리 하나요?

2021-09-17 07:12 UTC, Oraange commented on bookings/views.py
> +                kid              = kid
그 부분은 따로 처리하는 것을 놓쳐가지고 default = 0 을 주려고 하는데 null = True로 하는게 더 나을까요?

2021-09-17 07:37 UTC, S2-J1NG commented
치헌님 `conflict` 해결 후 유닛테스트 작성해주세요!

2021-09-18 12:03 UTC, Oraange commented
<img width="574" alt="스크린샷 2021-09-18 오후 9 02 52" src="https://user-images.githubusercontent.com/42742076/133888164-c75d5a29-534a-4670-be9d-727cd908cda5.png">

2021-09-18 14:32 UTC, Oraange commented
<img width="601" alt="스크린샷 2021-09-18 오후 11 07 04" src="https://user-images.githubusercontent.com/42742076/133891541-a6d8f4ef-b397-4213-af21-13b656f58d74.png">
- 감격의 unit test 통과 현장

![스크린샷 2021-09-18 오후 11 24 56](https://user-images.githubusercontent.com/42742076/133892099-f832de62-cef3-4b18-82e0-06777f859033.png)
- [Postman] POST - CREATED(예매 성공)

![스크린샷 2021-09-18 오후 11 25 35](https://user-images.githubusercontent.com/42742076/133892117-280be4a5-82ef-4c94-a8f9-20609909677c.png)
- [Postman] POST - DoesNotExists(영화관이나 영화의 id가 없는데 예매하려 할 때 에러)

![스크린샷 2021-09-18 오후 11 26 52](https://user-images.githubusercontent.com/42742076/133892170-5336db18-f315-48ed-8438-dbbf954a86ed.png)
- [Postman] POST - DoesNotMatched(사용자가 선택한 인원 수(성인, 청소년, 어린이 총 인원의 합)가 선택한 좌석의 수와 맞지 않을 때 에러)

![스크린샷 2021-09-18 오후 11 28 12](https://user-images.githubusercontent.com/42742076/133892217-e2a0de0c-fe1c-4f3e-b817-894cc804440a.png)
[Postman] POST - AlreadyExists(선택한 좌석이 이미 예매된 좌석일 때 에러)

![스크린샷 2021-09-18 오후 11 28 55](https://user-images.githubusercontent.com/42742076/133892241-bf1f09ee-d23e-4b21-aebb-7f028503c70c.png)
[Postman] POST - KeyError(전송된 데이터에서 메타데이터가 누락되었을 때 에러)

![스크린샷 2021-09-18 오후 11 29 50](https://user-images.githubusercontent.com/42742076/133892275-52a216be-e65b-405c-b93e-a58e95ad23c0.png)
[Postman] POST - ValueError(데이터의 타입이 유효하지 않은 타입일 때 에러)

![스크린샷 2021-09-18 오후 11 31 13](https://user-images.githubusercontent.com/42742076/133892321-2c710f53-6223-4464-a6b9-0ce74b2581f9.png)
[Postman] GET - 조회 성공

![스크린샷 2021-09-18 오후 11 31 55](https://user-images.githubusercontent.com/42742076/133892339-70ae8dbb-e651-46e8-94e8-cf9fcb0229cd.png)
[Postman] GET - HistoryDoesNotExists(예매 정보가 존재하지 않을 때 에러)

2021-09-27 02:09 UTC, S2-J1NG commented
유닛테스트 통과 정말 축하 드립니다! 🥳 
질문 2개 주셨는데 순서대로 답변 드리면..!
1. 204 error
status code 204는 request 잘 받았고 response로 담아 줄 거는 없을 때 사용하는 상태 코드 입니다.
그래서 jwt의 payload에 새롭게 담아줄 내용이 없어 jwt의 headers에서 메세지가 끝나게 됩니다.
jwt에서 header와 payload까지 encode되어서 사용할 때는 decode 하는데 204에서는 decode할 payload가 없으니깐 jwt decode error가 나오게 됩니다. 아래의 추가 자료 확인하고 블로깅해보세요! 너무 좋은 주제예요 👍
https://restfulapi.net/http-status-204-no-content/
https://apihandyman.io/empty-lists-http-status-code-200-vs-204-vs-404/

2. 동일 유저가 같은 좌석 중복 선택
좌석에 대해서는 동일유저라고 할지라도 한 번만 선택되어야 하므로 중복 제거보다는 에러 처리를 하는 것이 더 적절합니다.
좌석이 한 번 이상 선택되는 것 자체가 에러로 보는 것이 맞습니다.

2021-09-27 02:09 UTC, merged