[윤현묵] movie view 작성
wecode-bootcamp-korea/24-2nd-METABOX-backend pull request #5
Opened 2021-09-18 06:44 UTC by fall031-muk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- movie view 작성 (각 영화별 정보 get)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 각 movie에 해당하는 정보를 보여주는 기능 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-27 02:14 UTC, S2-J1NG requested changes
현묵님 유닛테스트 작성 너무너무 힘드셨보네요ㅎ 그래도 잘 작성 해주셨습니다!
conflict 해결 후 머지 하겠습니다! 포스트맨 통신 결과까지 첨부해주시면 더더욱 좋을 거 같네요ㅎ

2021-09-28 07:50 UTC, fall031-muk commented
아직 일부 더미 데이터 안넣어서 빈칸으로 나온 부분이 있고, 유닛테스트와 다른 더미데이터 추가로 넣어 포스트맨 결과 출력하였습니다

2021-09-28 08:09 UTC, S2-J1NG requested changes
현묵님 최종 수정 해주세요!

2021-09-28 08:09 UTC, S2-J1NG commented on config/urls.py
> +    path('movies', include('movies.urls'))
`bookings` 로직 메인에 머지된 부분이므로 url에 movies와 같이 있어야 하지 않나요?
아래와 같이 url 파일에 있어야 합니다.
```
urlpatterns = [
 path('bookings', include('bookings.urls'),
 path('movies', include('movies.urls'))
]
```

2021-09-28 08:47 UTC, fall031-muk commented on config/urls.py
> +    path('movies', include('movies.urls'))
네네 bookings 추가하였습니다.

2021-09-28 08:48 UTC, S2-J1NG approved these changes

2021-09-28 08:48 UTC, S2-J1NG commented
수고하셨습니다! runserver 정상 확인 하셨죠? 다음 기능 구현 해주세요!

2021-09-28 08:48 UTC, merged