ADD : KAKAO API
wecode-bootcamp-korea/24-2nd-METABOX-backend pull request #7
Opened 2021-09-24 10:04 UTC by Gouache-studio

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [X] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

<img width="499" alt="스크린샷 2021-09-24 오후 7 02 27" src="https://user-images.githubusercontent.com/73429600/134657077-d43f6592-df01-4ac1-bc04-e8fda2d4393c.png">

2021-09-27 02:31 UTC, S2-J1NG requested changes

2021-09-27 02:31 UTC, S2-J1NG commented on users/views.py
> +        # 가능한 발생할 수 있는 에러 잡자!!!
불필요한 주석은 삭제해주세요!

2021-09-27 02:31 UTC, S2-J1NG commented on users/tests.py
> +
view에서 작성하신 코드에서는 key에러와 value 에러를 잡았으니 이에 대한 테스트 작성해주세요
MockedResponse의 json 함수 return이 없다면 에러가 나겠죠?

2021-09-27 02:33 UTC, S2-J1NG requested changes

2021-09-27 02:33 UTC, S2-J1NG commented on users/views.py
> +                user = User.objects.get(kakao_id = kakao_id)
이 부분은 get_or_create()로 합칠 수 있습니다. 반영해주세요~!

2021-09-27 02:33 UTC, S2-J1NG commented on users/views.py
> +                token = jwt.encode({"id" : user.kakao_id, 'exp':datetime.utcnow() + timedelta(days=3)}, SECRET_KEY, algorithm= ALGORITHM)
jwt 토큰 발행 시 user 테이블의 pk로 토큰 발행해주세요. kakao_id도 DB에 저장되는 유저의 개인정보이니 되도록 노출 안 시키는 게 좋습니다.

2021-09-28 04:22 UTC, Gouache-studio commented on users/views.py
> +        # 가능한 발생할 수 있는 에러 잡자!!!
삭제했습니다!

2021-09-28 05:08 UTC, S2-J1NG approved these changes
소셜 로그인 로직 및 유닛테스트까지 작성 수고하셨습니다!
일반 회원가입 로그인에 대한 유닛테스트까지 별도의 브랜치 생성해서 작성해주세요!

conflict 해결 완료하면 이 브랜치는 머지 하도록 하겠습니다!

2021-09-28 12:17 UTC, Gouache-studio commented
<img width="714" alt="스크린샷 2021-09-28 오후 9 09 18" src="https://user-images.githubusercontent.com/73429600/135084897-2d797111-7d5d-4dee-a293-ecef47b98c66.png">
<img width="709" alt="스크린샷 2021-09-28 오후 9 09 39" src="https://user-images.githubusercontent.com/73429600/135084908-2c875868-ea2e-4ab3-9db1-8c1e0df3046b.png">

git rebase --continue 숫자로 표시된 브랜치가 새로 파져서 생성되었습니다. 어떤 이유로 브랜치가 생성되었는지 궁금합니다!

2021-09-29 01:52 UTC, S2-J1NG commented
종민님 rebase 중에 conflict 해결이 다 안 끝났는데 commit을 해서 생긱 오류 같습니다.
아직 rebase 덜 끝났으며 conflict 해결 계속 진행 해주세요!

2021-09-30 01:21 UTC, S2-J1NG approved these changes
불필요한 주석은 앞으로 반드시 삭제해주세요!

2021-09-30 01:21 UTC, merged