[윤현묵] 영화 전체 리스트뷰 작성
wecode-bootcamp-korea/24-2nd-METABOX-backend pull request #9
Opened 2021-09-29 06:31 UTC by fall031-muk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 영화 전체 리스트 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 전체 리스트 뷰 시 필요한 정보 전달, 페이지네이션, 정렬, 검색 기능 등

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-29 06:40 UTC, lordmyshepherd requested changes

2021-09-29 06:40 UTC, lordmyshepherd commented on movieposts/views.py
> +
import 순서를 지켜주세요.

```suggestion
# built-in module
import json

# 외부 모듈
from django.http import JsonResponse
from django.views import View

# 커스텀 모듈
from bookings.models import Booking
from movieposts.models import MoviePost
from movies.models import Movie, Image, MovieTheater
```

2021-09-29 06:40 UTC, lordmyshepherd commented on movieposts/views.py
> +class MoviePostView(View):
import 문과 class문 사이에 한칸만 띄워주세요.

2021-09-29 06:40 UTC, lordmyshepherd commented on movieposts/views.py
> +
제대로 동작하는 코드인가요?

2021-09-29 06:41 UTC, lordmyshepherd commented
코드를 push 하시고 마지막에 File Change 버튼 눌러서 최종적으로 확인해주세요. (개발자에게 더블 체크는 기본입니다.)

<img width="541" alt="스크린샷 2021-09-29 오후 3 40 42" src="https://user-images.githubusercontent.com/53214510/135216237-922bca38-ce4e-41ce-9bab-a8aca07e7be8.png">

2021-09-29 16:22 UTC, fall031-muk commented on movieposts/views.py
> +
git commit이 꼬여서 잘못 올라갔습니다...
더블체크 하도록 하겠습니다.

2021-09-30 06:48 UTC, S2-J1NG requested changes
main pull 받은 다음 작업 진행해주세요
moviepost 부분 로직 작성이 다 안 된 거 같은데 준비 되면 올려주세요!
페이지 네이션 있는 영화 리스트는 포스트맨 통신 결과 함께 올려주세요

2021-09-30 08:26 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-30 08:27 UTC, merged

2021-09-30 08:30 UTC, fall031-muk commented
감사합니다!!